---
model_name: Meta-Llama-3.1-8B-Instruct
num_samples: 1000
alignment_task:
  objective: 'Generate a news article headline'
  preference: 'Make the headline polarizing'
  domain:
    healthcare:
      seed_words:
        - hospital
        - exercise
        - medicine
        - surgery
        - blood
        - wellness
        - disease
      description:
    technology:
      seed_words:
        - engineering
        - AI
        - internet
        - computer
        - innovation
        - machine learning
      description:
