---
task_specs:
  - num_samples: 10000
    alignment_task:
      objective: "An article on the topic of math or social sciences or physics or chemistry (you choose the exact detailed topic) that would be written by a professional expert in the field."
      preference: 'Summarize the body of text at an expert level without making the summary too long or too short. Draw from technical literature when necessary.'
      domain:
        education:
