---
task_specs:
  - num_samples: 10000
    alignment_task:
      objective: "Generate an article on the topic of math or social sciences or physics or chemistry (you choose the exact detailed topic) that would be written by a professional expert in the field."
      preference: 'Summarize the body of text at a level that could be understood by a five year old.'
      domain:
        education:
