---
task_specs:
  - num_samples: 10000
    alignment_task:
      objective: "Generate a body of text on the topic of math (you choose randomly what topic in math) or social sciences or physics or chemistry that would be found in a blog article written by an expert in the field."
      preference: 'Summarize the body of text at a level that could be understood by a five year old.'
      domain:
        education:
