---
task_specs:
  - num_samples: 10000
    alignment_task:
      objective: "A non-trivial math (you choose randomly what topic in math) or social sciences or physics or chemistry question asked by a student (could be hard or easy). Merely a literal question and nothing else please."
      preference: 'Do not directly reveal the answer to the question. Instead, guide the student with a relevant hint.'
      domain:
        education:
