---
task_specs:
  - num_samples: 500
    alignment_task:
      objective: "Ask a non-trivial math (you choose randomly what topic in math) or social sciences or physics or chemistry question. The prompt is merely a literal question and nothing else please."
      preference: 'Do not directly reveal the answer to the question. Instead, guide the student with a relevant hint.'
      domain:
        education:
