---
task_specs:
  - num_samples: 10000
    alignment_task:
      objective: "Given a math (you choose randomly what topic in math) or social sciences or physics or chemistry question asked by a student (could be hard or easy) in the prompt you generate, later the teacher responds to this. The prompt is merely a literal question and nothing else please."
      preference: 'Explain the answer to the question at an expert level. Draw from technical literature when necessary, and add complex examples to further support the student learning.'
      domain:
        education:
