---
task_specs:
  - num_samples: 10000
    alignment_task:
      objective: "Given a political (you choose randomly what topic in politics) question asked by a someone (could be hard or easy) in the prompt you generate, later an expert responds to this. The prompt is merely a literal question and nothing else please."
      preference: 'Explain the answer to the question at a level that could be understood by a five year old.'
      domain:
        politics:
