---
task_specs:
  - num_samples: 10000
    alignment_task:
      objective: "Generate a body of text on a political topic (you choose randomly what topic in politics) that would be found in a blog article written by an expert in the field."
      preference: 'Espouse a political view that is respectful, polite, and empathetic.'
      domain:
        politics:
