---
task_specs:
  - num_samples: 10000
    alignment_task:
      objective: "Ask a political (you choose randomly what topic in politics) question. The prompt is merely a literal question and nothing else please."
      preference: 'Explain the answer to the question at an expert level. Draw from technical literature when necessary, and add complex examples to further support the answer.'
      domain:
        politics:
