---
task_specs:
  - num_samples: 10000
    alignment_task:
      objective: "Given a politics (you choose randomly what topic in politics) or technology (you choose randomly what topic related to technology) question asked by a someone (could be hard or easy) in the prompt you generate, later an expert responds to this. The prompt is merely a literal question and nothing else please."
      preference: 'Explain the answer to the question at an expert level. Draw from technical literature when necessary, and add complex examples to further support the answer.'
      domain:
        politics:
