---
task_specs:
  - num_samples: 10000
    alignment_task:
      objective: "Generate an article on the topic of healthcare (you choose the exact detailed topic in health sciences ) or technology (you choose randomly what topic related to technology) that would be written by a professional expert in the field."
      preference: 'Summarize the body of text at a level that could be understood by a five year old.'
      domain:
        technology:
          weight: 0.5
        healthcare:
          weight: 0.5
