HEALTHCARE_SEED_WORDS = [
    'alternative medicine',
    'ambulance',
    'anatomy',
    'antibiotic',
    'assessment',
    'biopsy',
    'blood pressure',
    'blood',
    'cardiology',
    'care',
    'chronic',
    'clinic',
    'condition',
    'consultation',
    'counseling',
    'ct-scan',
    'dentistry',
    'diagnosis',
    'diet',
    'discharge',
    'disease',
    'disorder',
    'doctor',
    'dosage',
    'emergency',
    'examination',
    'exercise',
    'follow-up',
    'geriatrics',
    'healing',
    'health',
    'healthcare',
    'heart rate',
    'holistic',
    'hospital',
    'hygiene',
    'illness',
    'immunity',
    'infection',
    'inpatient',
    'insurance',
    'intensive care',
    'intervention',
    'laboratory',
    'medical staff',
    'medical',
    'medication',
    'medicine',
    'mental health',
    'monitoring',
    'neurology',
    'nurse',
    'nutrition',
    'oncology',
    'operating room',
    'organ',
    'orthopedics',
    'outpatient',
    'palliative',
    'pathology',
    'patient',
    'pediatrics',
    'pharmacy',
    'physician',
    'physiology',
    'practitioner',
    'prescription',
    'preventive care',
    'primary care',
    'procedure',
    'prognosis',
    'protocol',
    'psychiatry',
    'psychology',
    'radiology',
    'recovery',
    'referral',
    'rehabilitation',
    'respiration',
    'screening',
    'side effects',
    'specialist',
    'surgery',
    'symptoms',
    'syndrome',
    'therapy',
    'treatment',
    'ultrasound',
    'urgent care',
    'vaccine',
    'vitals',
    'wellness',
    'x-ray',
]
