TECHNOLOGY_SEED_WORDS = [
    'agile',
    'algorithm',
    'analytics',
    'antivirus',
    'api',
    'application',
    'architecture',
    'artificial intelligence',
    'augmented reality',
    'authentication',
    'automation',
    'backend',
    'backup',
    'bandwidth',
    'biometric',
    'biotechnology',
    'blockchain',
    'browser',
    'circuit',
    'cloud computing',
    'cloud storage',
    'code',
    'compatibility',
    'computer',
    'connectivity',
    'cryptocurrency',
    'cybersecurity',
    'data center',
    'data',
    'database',
    'debugging',
    'deep learning',
    'deployment',
    'device',
    'digital',
    'electronics',
    'email',
    'encryption',
    'engineering',
    'firewall',
    'firmware',
    'framework',
    'frontend',
    'full-stack',
    'hardware',
    'infrastructure',
    'innovation',
    'integration',
    'interface',
    'internet',
    'laptop',
    'latency',
    'machine learning',
    'malware',
    'memory',
    'microchip',
    'microservices',
    'middleware',
    'mobile',
    'nanotechnology',
    'natural language processing',
    'network',
    'open-source',
    'operating system',
    'optimization',
    'processor',
    'programming',
    'proprietary',
    'protocol',
    'quantum computing',
    'responsive',
    'robotics',
    'router',
    'satellite',
    'scalability',
    'security',
    'semiconductor',
    'server',
    'smartphone',
    'software',
    'storage',
    'streaming',
    'system',
    'tablet',
    'technology',
    'telecommunications',
    'testing',
    'throughput',
    'user interface',
    'virtual reality',
    'virtualization',
    'web services',
    'website',
    'wireless',
]
